mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('toko.urls')),
    path("admin/", admin.site.urls),
]

mysite/toko/urls.py
from django.urls import path

from . import views

# Lihat tutorial 3 bagian Use templat system

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:produk_id>', views.delete_produk, name='delete'),
    path('edit/<int:produk_id>', views.edit_produk, name='edit'),
    path('add_data', views.add_produk, name='add_data'),
]

mysite/toko/models.py
from django.db import models

class Kategori(models.Model):
    nama_katagori = models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.nama_katagori

class Status(models.Model):
    nama_status = models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.nama_status

class Produk(models.Model):
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    nama_produk = models.TextField()
    harga = models.IntegerField()
    def __str__(self) -> str:
        return self.nama_produk
    
    

mysite/toko/forms.py
from django import forms  
from .models import Produk
  
class ProdukForm(forms.ModelForm):  
    class Meta:  
        model = Produk  
        fields = "__all__"  
        
        # this function will be used for the validation
    def clean(self):
        # data from the form is fetched using super function
        super(ProdukForm, self).clean()
         
        # extract the username and text field from the data
        nama_produk = self.cleaned_data.get('nama_produk')
        harga = self.cleaned_data.get('harga')
 
        # conditions to be met for the username length
        if len(nama_produk) < 10:
            self._errors['nama_produk'] = self.error_class([
                'Minimum 5 characters required'])
        if harga < 1000:
            self._errors['harga'] = self.error_class([
                'Harga minimum of 1000'])
 
        # return any errors if found
        return self.cleaned_data

mysite/toko/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Status, Produk
from django.urls import reverse
from .forms import ProdukForm
from django.contrib import messages

def index(request):
    status = Status.objects.get(nama_status = "bisa dijual")
    context = {
        'statuss' : status
    }
    return render(request, 'toko/index.html', context)

def add_produk(request):
    if request.method == 'POST':
        form = ProdukForm(request.POST)
        if form.is_valid():
            produk = form.save(commit=False)
            produk.save()
            messages.success(request, "Data Added.")
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, "periksa kembali data anda")
            return render(request, 'toko/form.html', {'form':form}) 
    form = ProdukForm(None)   
    return render(request, 'toko/form.html', {'form':form})
    
def delete_produk(request, produk_id):
    produk = Produk.objects.get(id=produk_id)
    if request.method == "POST":
        produk.delete()
        messages.error(request, "Document deleted.")
        return HttpResponseRedirect(reverse('index'))
    return HttpResponseRedirect(reverse('index'))

def edit_produk(request, produk_id): 
    instance = get_object_or_404(Produk, id=produk_id)
    form = ProdukForm(request.POST or None, instance=instance)
    if form.is_valid():
        produk = form.save(commit=False)
        produk.save()
        messages.success(request, "Data updated.")
        return HttpResponseRedirect(reverse('index'))
    return render(request, 'toko/form.html', {'form': form}) 
 

mysite/toko/templates/toko/form.html
<!DOCTYPE html>
<html>
  {% for msg in messages %}
  <div style="background-color: #ffc107; color: #856404; padding: 10px; border: 1px solid #ffeeba; border-radius: 5px">{{ msg }}</div>
  {% endfor %}
  <body>
    <h2>Forms</h2>
    <a href="/" style="background-color: #007bff; color: #fff; padding: 3px 8px; text-decoration: none; border-radius: 3px; margin-right: 5px">home</a>
    <form action="" method="POST">
      {% csrf_token %} {{ form.as_p }}
      <input
        type="submit"
        value="Submit"
        style="background-color: #007bff; color: #fff; padding: 3px 8px; text-decoration: none; border-radius: 3px; margin-right: 5px"
        onclick="return confirm('Apakah anda yakin?');"
      />
    </form>
  </body>
</html>

mysite/toko/templates/toko/index.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      table,
      th,
      td {
        border: 1px solid black;
      }

      .button-column {
        text-align: center;
      }

      .button-column a {
        display: inline-block;
        padding: 2px 5px;
        text-decoration: none;
        color: #fff;
        background-color: #007bff;
        border-radius: 4px;
        cursor: pointer;
      }
    </style>
  </head>
  {% for msg in messages %}
  <div style="background-color: #ffc107; color: #856404; padding: 10px; border: 1px solid #ffeeba; border-radius: 5px">{{ msg }}</div>
  {% endfor %}
  <body>
    <h1>List available produk</h1>
    <div>
      <a
        href="{% url 'add_data' %}"
        style="margin: 5px; display: inline-block; padding: 2px 5px; text-decoration: none; color: #fff; background-color: #007bff; border-radius: 4px; cursor: pointer"
        >Insert</a
      >
    </div>

    <table>
      <colgroup>
        <col style="background-color: yellow" />
      </colgroup>
      <tr>
        <th>Nama Produk</th>
        <th>Harga</th>
        <th>Kategori</th>
        <th class="button-column">Actions</th>
      </tr>

      {% if statuss %} {% for status in statuss.produk_set.all %}
      <tr>
        <td>{{ status.nama_produk }}</td>
        <td>{{ status.harga }}</td>
        <td>{{ status.kategori.nama_katagori}}</td>
        <td class="button-column" inline>
          <a href="/edit/{{ status.id }}" style="background-color: #007bff; color: #fff; padding: 3px 8px; text-decoration: none; border-radius: 3px; margin-right: 5px">Update</a>
          <form action="/delete/{{ status.id }}" method="post" style="display: inline-block">
            {% csrf_token %}
            <input
              type="submit"
              style="background-color: #dc3545; color: #fff; padding: 5px 10px; border: none; border-radius: 3px; cursor: pointer"
              value="Delete"
              onclick="return confirm('Apakah anda yakin ingin menghapus?');"
            />
          </form>
        </td>
      </tr>
      {% endfor %} {% else %}
      <p>no status are available.</p>
      {% endif %}
    </table>
  </body>
</html>